#version: "3.8"
services:
  psql_db:
    image: 'postgres:latest'
    container_name: psql_db
    restart: always
    shm_size: 128mb
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'


  demoapp:
    container_name: demo_app
    build:
      context: C:/Online/sping_boot_with_thymeleaf
      dockerfile: DockerFile
    ports:
      - '9090:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
    depends_on:
      - psql_db
